server:
  port: 8081
spring:
  application:
    name: STUDENT-SERVICE
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${postgres_host:localhost}:5432/postgres
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher