spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Nikileshkumar/configRepo

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka_host:localhost}:8761/eureka/